package ai.forvum.sdk;

import java.util.Set;

/**
 * The host SPI a media-generation plugin implements so the model-callable generation tools (#187,
 * {@code image.generate} / {@code video.generate} / {@code music.generate}) can turn a prompt into a
 * media asset without coupling the tool surface to any one backend. A dedicated SPI, NOT an overload of
 * {@code ModelProvider} — a generation backend produces bytes, not a chat stream (the {@code
 * MemoryProvider} P2-5 posture). The interface is sealed: a third party extends
 * {@link AbstractGenerationProvider} (the one permitted type), so the closed set stays enumerable while
 * remaining open to external implementations.
 *
 * <h2>Discovery</h2>
 * A concrete implementation is a Layer-3 Forvum extension that depends ONLY on {@code forvum-sdk}
 * (+ the Layer-0 contracts it re-exposes). It carries:
 * <ul>
 *   <li>{@link ForvumExtension} on the provider class, so the build-time plugin scanner records it and
 *       emits the native-image reflection hints (ULTRAPLAN section 6.3);</li>
 *   <li>a {@code META-INF/forvum/plugin.json} manifest declaring a provider of
 *       {@code "type": "generation"} pointing at the implementing class;</li>
 *   <li>{@code @ApplicationScoped} (or another bean-defining scope) plus a {@code META-INF/beans.xml}
 *       so ArC discovers the bean.</li>
 * </ul>
 * A bundled provider stays INERT until an operator configures it (e.g. via
 * {@code $FORVUM_HOME/tools/media-gen.json}): unconfigured, {@link #isActive()} reports {@code false}
 * and {@link #generate(GenerationRequest)} throws an actionable error naming the file to create —
 * never a network call, never a crash at boot.
 *
 * <h2>The generate contract</h2>
 * {@link #generate(GenerationRequest)} maps a prompt (+ the requested {@link MediaKind}) to one
 * {@link GeneratedMedia} asset. {@link #supportedKinds()} declares which kinds the backend can produce
 * (an images-only backend returns {@code Set.of(MediaKind.IMAGE)}); callers select a provider by kind
 * first, so a provider may treat an unsupported kind reaching {@code generate} as a programming error.
 * Backend-specific knobs (model, size, format) are operator configuration, never request fields — the
 * model controls only the prompt.
 *
 * <h2>Concurrency &amp; native expectations</h2>
 * {@code generate} is BLOCKING and is invoked on a virtual thread (CLAUDE.md section 3.8): an
 * implementation calls its backend with blocking IO (a blocking REST client) and returns a value
 * directly — NEVER a reactive return type (Mutiny {@code Uni}/{@code Multi} is a PR-reject). The module
 * must be native-clean: REST DTOs are records carrying {@code @RegisterForReflection}, no runtime
 * reflection, no {@code ServiceLoader}, no {@code sun.misc.Unsafe}, no runtime bytecode generation.
 */
public sealed interface GenerationProvider permits AbstractGenerationProvider {

    /** Stable id of the contributing extension, matching its {@code META-INF/forvum/plugin.json}. */
    String extensionId();

    /**
     * Whether this provider is configured and ready to generate right now. A bundled-but-unconfigured
     * backend reports {@code false} so a caller can prefer a configured sibling (the
     * {@code MemoryProvider#isActive()} posture); the default is {@code true} for providers with no
     * off/unconfigured state to report.
     *
     * @return {@code true} if this provider should be selected when installed and active
     */
    default boolean isActive() {
        return true;
    }

    /**
     * The media kinds this backend can produce. Callers route a request to a provider whose set contains
     * the requested {@link MediaKind}; when no installed provider supports a kind, the tool surfaces an
     * actionable "backend does not support" error instead of calling anyone.
     *
     * @return the supported kinds, never {@code null} or empty
     */
    Set<MediaKind> supportedKinds();

    /**
     * Generate one media asset from {@code request}.
     *
     * <p>Blocking; invoked on a virtual thread. Returns the generated bytes plus the file extension to
     * persist them under — never {@code null}. Throws a {@link RuntimeException} with an actionable
     * message on any configuration or backend failure (the engine audits the tool call {@code error} and
     * renders the message to the model; the turn completes).
     *
     * @param request the kind + prompt to generate (non-null; its kind is in {@link #supportedKinds()})
     * @return the generated asset, never {@code null}
     */
    GeneratedMedia generate(GenerationRequest request);
}
